# If set to true, players can go through
# the gate without a ticket while sneaking.
allow-illegal-bypass: true

# Set custom sounds
# Opened illegaly
illegal-sound: "minecraft:item.trident.thunder"
# Opened with the correct ticket
success-sound: "minecraft:entity.experience_orb.pickup"
# Invalid or no ticket
invalid-sound: "minecraft:block.redstone_torch.burnout"

# Universal key that opens every gate
master-key: 123456

gates:
  default:
    gate: ACACIA_FENCE_GATE
    block: COBBLESTONE
  subway:
    gate: ACACIA_FENCE_GATE
    block: POLISHED_ANDESITE
    id: '359235'
    name: Subway Ticket
    lore: Ticket
    one-time-use: true

# Plugin version - Do not change!
version: '${project.version}'